<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;

class HomepageController extends Controller
{
    public function index() {
        $products = [
            [
                'id' => '1',
                'name' => 'Pav Bhaji',
                'description' => 'Pav bhaji is made with vegetables like potatoes, onions, tomatoes, peas, cauliflower, and capsicum, cooked with pav bhaji masala, turmeric, red chilli powder, cumin seeds, and sometimes garam masala, along with butter, oil, ginger-garlic paste, salt, and lemon juice, served with butter-toasted pav, chopped onions, coriander leaves, and lemon wedges.',
                'priceDiscount' => 18.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400&h=250&fit=crop',
                'category' => 'Indian',
                'popular' => true,
                'rating' => 4.4,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '15-20 min',
            ],
            [
                'id' => '2',
                'name' => 'Kung Pao Chicken',
                'description' => 'Spicy stir-fried chicken with peanuts and vegetables',
                'priceDiscount' => 16.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&h=250&fit=crop',
                'category' => 'Chinese',
                'popular' => true,
                'rating' => 4.6,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '12-18 min',
            ],
            [
                'id' => '3',
                'name' => 'Classic Cheeseburger',
                'description' => 'Beef patty with cheese, lettuce, tomato, and special sauce',
                'priceDiscount' => 14.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=250&fit=crop',
                'category' => 'Burgers',
                'popular' => false,
                'rating' => 4.5,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '10-15 min',
            ],
            [
                'id' => '4',
                'name' => 'Salmon Sashimi',
                'description' => 'Fresh salmon sliced thin and served raw',
                'priceDiscount' => 24.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=250&fit=crop',
                'category' => 'Sushi',
                'popular' => true,
                'rating' => 4.9,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '5-10 min',
            ],
            [
                'id' => '5',
                'name' => 'Chicken Tacos',
                'description' => 'Three soft tacos with grilled chicken, salsa, and cilantro',
                'priceDiscount' => 13.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=250&fit=crop',
                'category' => 'Tacos',
                'popular' => false,
                'rating' => 4.4,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '8-12 min',
            ],
            [
                'id' => '6',
                'name' => 'Caesar Salad',
                'description' => 'Crisp romaine lettuce with parmesan cheese and croutons',
                'priceDiscount' => 12.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=250&fit=crop',
                'category' => 'Salads',
                'popular' => false,
                'rating' => 4.7,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '5-8 min',
            ],
            [
                'id' => '7',
                'name' => 'Chocolate Cake',
                'description' => 'Rich chocolate cake with chocolate frosting',
                'priceDiscount' => 8.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=250&fit=crop',
                'category' => 'Desserts',
                'popular' => true,
                'rating' => 4.6,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '3-5 min',
            ],
            [
                'id' => '8',
                'name' => 'Cappuccino',
                'description' => 'Rich espresso with steamed milk and foam',
                'priceDiscount' => 5.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1545665225-b23b99e4d45e?w=400&h=250&fit=crop',
                'category' => 'Coffee',
                'popular' => false,
                'rating' => 4.3,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '2-4 min',
            ],
        ];

        $props = [
            'products' => $products
        ];
        return Inertia::render('homepage/home', $props);
    }

    public function productDetail() {
        return Inertia::render('homepage/product-details');
    }

     public function productListing() {
        $products = [
            [
                'id' => '1',
                'name' => 'Pav Bhaji',
                'description' => 'Pav bhaji is made with vegetables like potatoes, onions, tomatoes, peas, cauliflower, and capsicum, cooked with pav bhaji masala, turmeric, red chilli powder, cumin seeds, and sometimes garam masala, along with butter, oil, ginger-garlic paste, salt, and lemon juice, served with butter-toasted pav, chopped onions, coriander leaves, and lemon wedges.',
                'priceDiscount' => 18.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400&h=250&fit=crop',
                'category' => 'Indian',
                'popular' => true,
                'rating' => 4.4,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '15-20 min',
            ],
            [
                'id' => '2',
                'name' => 'Kung Pao Chicken',
                'description' => 'Spicy stir-fried chicken with peanuts and vegetables',
                'priceDiscount' => 16.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&h=250&fit=crop',
                'category' => 'Chinese',
                'popular' => true,
                'rating' => 4.6,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '12-18 min',
            ],
            [
                'id' => '3',
                'name' => 'Classic Cheeseburger',
                'description' => 'Beef patty with cheese, lettuce, tomato, and special sauce',
                'priceDiscount' => 14.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=250&fit=crop',
                'category' => 'Burgers',
                'popular' => false,
                'rating' => 4.5,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '10-15 min',
            ],
            [
                'id' => '4',
                'name' => 'Salmon Sashimi',
                'description' => 'Fresh salmon sliced thin and served raw',
                'priceDiscount' => 24.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=250&fit=crop',
                'category' => 'Sushi',
                'popular' => true,
                'rating' => 4.9,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '5-10 min',
            ],
            [
                'id' => '5',
                'name' => 'Chicken Tacos',
                'description' => 'Three soft tacos with grilled chicken, salsa, and cilantro',
                'priceDiscount' => 13.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=250&fit=crop',
                'category' => 'Tacos',
                'popular' => false,
                'rating' => 4.4,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '8-12 min',
            ],
            [
                'id' => '6',
                'name' => 'Caesar Salad',
                'description' => 'Crisp romaine lettuce with parmesan cheese and croutons',
                'priceDiscount' => 12.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=250&fit=crop',
                'category' => 'Salads',
                'popular' => false,
                'rating' => 4.7,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '5-8 min',
            ],
            [
                'id' => '7',
                'name' => 'Chocolate Cake',
                'description' => 'Rich chocolate cake with chocolate frosting',
                'priceDiscount' => 8.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=250&fit=crop',
                'category' => 'Desserts',
                'popular' => true,
                'rating' => 4.6,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '3-5 min',
            ],
            [
                'id' => '8',
                'name' => 'Cappuccino',
                'description' => 'Rich espresso with steamed milk and foam',
                'priceDiscount' => 5.99,
                'priceOrigin' => 5,
                'image' => 'https://images.unsplash.com/photo-1545665225-b23b99e4d45e?w=400&h=250&fit=crop',
                'category' => 'Coffee',
                'popular' => false,
                'rating' => 4.3,
                'quantity' => 10,
                'foodType' => [],
                'preparationTime' => '2-4 min',
            ],
        ];

        $props = [
            'products' => $products,
        ];

        return Inertia::render('homepage/product-listing', $props);
    }
}
